heat_template_version: rocky
description: Georgia Technology Authority Event 2020 - Individual
#############################################################
## Index
##
## 1.0- Blue Team Networking/ports
## 1.1- Enterprise Networking/ports
## 1.2- DMZ Networking/ports
## 1.3- Red Team Networking/ports
## 1.4- Signals/Handles
## 2.0- Blue Team Resources
## 3.0- Enterprise Resources
## 4.0- DMZ Resources
## 5.0- Red Team Resources
#############################################################
parameters:

  username:
    type: string
    label: Security Onion Username
    description: Username used to log in to various Security Onion services
    default: gmips
  userpass:
    type: string
    label: Security Onion Password
    description: Password used to log in to various Security Onion services
    default: gmips123
  domainpass:
    type: string
    label: Domain Safe Mode Password
    description: Domain administrator password
    default: P@ssword123
  domain_name:
    type: string
    label: Domain Name
    description: Domain name
    default: gmips.gov
  domain_netbios_name:
    type: string
    label: Domain NetBIOS name
    description: NetBIOS name for created domain
    default: gmips
  sopass:
    type: string
    label: password for so user
    description: Password for the 'so' user on both so_master and so_gateway
    default: so

resources:
## 1.0 Blue Team Network
  blue_net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  blue_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: blue_net }
      cidr: 10.223.0.0/24
      dns_nameservers:
        - 10.101.255.254
  blue_gateway_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: blue_net }
      fixed_ips:
        - ip_address: 10.223.0.254
  blue_master_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: blue_net }
      fixed_ips:
        - ip_address: 10.223.0.250

## 1.1 Enterprise Network
  green_net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  green_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: green_net }
      cidr: 10.221.0.0/24
      dns_nameservers:
        - 10.221.0.10
        - 10.101.255.254
      gateway_ip: 10.221.0.254
  green_gateway_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: green_net }
      fixed_ips:
        - ip_address: 10.221.0.254
  green_domain_controller_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: green_net }
      fixed_ips:
        - ip_address: 10.221.0.10

## 1.2 DMZ Network
  white_net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  white_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: white_net }
      cidr: 10.222.0.0/24
      dns_nameservers:
        - 10.101.255.254
      gateway_ip: 10.222.0.254
  white_gateway_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: white_net }
      fixed_ips:
        - ip_address: 10.222.0.254
  white_server_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: white_net }
      fixed_ips:
        - ip_address: 10.222.0.15

## 1.3 Red Team Network
  red_net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  red_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: red_net }
      cidr: 10.224.0.0/24
      dns_nameservers:
        - 10.101.255.254
      gateway_ip: 10.224.0.254
  red_gateway_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: red_net }
      fixed_ips:
        - ip_address: 10.224.0.254
  kali_1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: red_net }
      fixed_ips:
        - ip_address: 10.224.0.10

## 2.0 Blue Team Resources
## gateway serves as core router and SO heavy node/sensor for attached networks
  gateway:
    type: OS::Nova::Server
    properties:
      name: so_gateway
      flavor: hack.c8.m16384.d128
      networks:
        - port: { get_resource: red_gateway_port } #ens3
        - port: { get_resource: green_gateway_port } #ens4
        - port: { get_resource: white_gateway_port } #ens5
        - port: { get_resource: blue_gateway_port } #ens6
        - network: Public #ens7
      image: so-gateway
      user_data_format: RAW

  so_master:
    type: OS::Nova::Server
    depends_on: gateway
    properties:
      name: so_master
      flavor: hack.c8.m16384.d128
      networks:
        - port: { get_resource: blue_master_port }
      image: so-master
      config_drive: true
      user_data_format: RAW

## individual analyst workstations - this template needs to be turned into a pipeline product
  analyst_workstation_0:
    type: OS::Nova::Server
    depends_on: blue_net
    properties:
      flavor: hack.c2.m8192.d32
      image: analyst-workstation
      name: analyst-workstation
      networks:
        - network: { get_resource: blue_net }

## 3.0 Enterprise Resources
  domain_controller:
    type: OS::Nova::Server
    depends_on: gateway
    properties:
      name: domain_controller
      flavor: hack.c4.m8192.d128
      networks:
        - port: { get_resource: green_domain_controller_port }
      image: GMIPS-DC
      user_data_format: RAW

  windows_workstation:
    type: OS::Nova::Server
    depends_on: domain_controller
    properties:
      name: GMIPS-10
      flavor: hack.c2.m8192.d64
      networks:
        - network: { get_resource: green_net }
      image: GMIPS-10
      user_data_format: RAW

## 4.0 DMZ Resources
  DMZ_server:
    type: OS::Nova::Server
    depends_on: gateway
    properties:
      name: DMZ-Server
      flavor: hack.c4.m8192.d32
      networks:
        - port: { get_resource: white_server_port }
      image: DMZ-Server
      user_data_format: RAW

## 5.0 Red Team Resources
  kali_1:
    type: OS::Nova::Server
    properties:
      name: Kali-1
      flavor: hack.c4.m16384.d128
      networks:
        - port: { get_resource: kali_1_port }
      image: Kali Rolling
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        echo "root:toor" | chpasswd
        cat > "/etc/apt/sources.list" << __EOF__
        deb http://http.kali.org/kali kali-rolling main non-free contrib
        deb-src http://http.kali.org/kali kali-rolling main non-free contrib
        __EOF__

outputs:
  analyst-0-ip:
    description: The routable IP for analyst 0
    value:
      get_attr: [analyst_workstation_0, addresses, public, 0, addr]